name: banner_board
description: "A fullscreen text banner app with marquee and animation effects."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.1+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  wakelock_plus: ^1.2.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: AlfaSlabOne
      fonts:
        - asset: assets/fonts/AlfaSlabOne-Regular.ttf
          # style: italic
          # weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf

    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

    - family: BigShouldersInline
      fonts:
        - asset: assets/fonts/BigShouldersInline-VariableFont_opsz,wght.ttf

    - family: Boldonse
      fonts:
        - asset: assets/fonts/Boldonse-Regular.ttf

    - family: BungeeSpice
      fonts:
        - asset: assets/fonts/BungeeSpice-Regular.ttf

    - family: Exo2Black
      fonts:
        - asset: assets/fonts/Exo2-Black.ttf

    - family: Exo2Bold
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf

    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf

    - family: Neonderthaw
      fonts:
        - asset: assets/fonts/Neonderthaw-Regular.ttf

    - family: PermanentMarker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf

    - family: PixelifySans
      fonts:
        - asset: assets/fonts/PixelifySans-VariableFont_wght.ttf

    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf

    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

    - family: RowdiesBold
      fonts:
        - asset: assets/fonts/Rowdies-Bold.ttf

    - family: RowdiesLight
      fonts:
        - asset: assets/fonts/Rowdies-Light.ttf

    - family: RowdiesRegular
      fonts:
        - asset: assets/fonts/Rowdies-Regular.ttf

    - family: RubikMonoOne
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf

    - family: SilkscreenBold
      fonts:
        - asset: assets/fonts/Silkscreen-Bold.ttf

    - family: SilkscreenRegular
      fonts:
        - asset: assets/fonts/Silkscreen-Regular.ttf

    - family: SpecialGothicExpandedOne
      fonts:
        - asset: assets/fonts/SpecialGothicExpandedOne-Regular.ttf

    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-VariableFont_wght.ttf

    - family: TiltNeon
      fonts:
        - asset: assets/fonts/TiltNeon-Regular-VariableFont_XROT,YROT.ttf

    - family: TitanOne
      fonts:
        - asset: assets/fonts/TitanOne-Regular.ttf
